tigo_une_general_bundles_work_flow:
    resource: "@TigoUneGeneralBundlesWorkFlowBundle/Resources/config/routing.yml"
    prefix:   /

tigo_une_general_bundles_authorization:
    resource: "@TigoUneGeneralBundlesAuthorizationBundle/Resources/config/routing.yml"
    prefix:   /

tigo_une_general_components_work_flow:
    resource: "@TigoUneGeneralComponentsWorkFlowBundle/Resources/config/routing.yml"
    prefix:   /

tigo_une_general_components_authorization:
    resource: "@TigoUneGeneralComponentsAuthorizationBundle/Resources/config/routing.yml"
    prefix:   /

tigo_une_general_bundles_helper:
    resource: "@TigoUneGeneralBundlesHelperBundle/Resources/config/routing.yml"
    prefix:   /

tigo_une_general_bundles_data_protection:
    resource: "@TigoUneGeneralBundlesDataProtectionBundle/Resources/config/routing.yml"
    prefix:   /

tigo_une_general_bundles_cache:
    resource: "@TigoUneGeneralBundlesCacheBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
